# Generated by Django 6.0.8 on 2026-10-05 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_feature_app', '0014_email_verification_code_purpose'),
        ('base_feature_app', '0014_order_access_challenge'),
    ]

    operations = [
    ]
