# Generated by Django 6.0.8 on 2026-10-08 14:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_feature_app', '0015_merge_auth_order_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordCodeAttemptBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('registration', 'Registration'), ('password_reset', 'Password reset')], max_length=20)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('attempt_window_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('send_count', models.PositiveSmallIntegerField(default=0)),
                ('send_window_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_code_budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'purpose'), name='unique_password_code_budget')],
            },
        ),
    ]
